spring:
  application:
    name: dubbo_auto_configuration_provider_demo2
server:
  port: 10090
#Dubbo provider2 configuration
dubbo:
  application:
    name: dubbo_provider2
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20888
#扫描注解包通过该设置将服务注册到zookeeper
#  scan:
  #  base-packages: com.demo.service